version: '3.8'

services:
  brain:
    build: ./brain
    ports:
      - "${BRAIN_PORT}:5555"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - PORT=5555
      - HOST=0.0.0.0
    networks:
      - osint-network
    restart: unless-stopped

  orchestra:
    build: ./orchestra
    ports:
      - "${ORCHESTRA_PORT}:5558"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - BRAIN_URL=brain:5555
      - PORT=5558
      - HOST=0.0.0.0
    depends_on:
      - brain
    networks:
      - osint-network
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "${API_PORT}:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - ORCHESTRATOR_URL=orchestra:5558
      - PORT=8080
      - HOST=0.0.0.0
    depends_on:
      - orchestra
    networks:
      - osint-network
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "${WEB_PORT}:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_URL=http://api:8080
      - SERVER_PORT=8080
    depends_on:
      - api
    networks:
      - osint-network
    restart: unless-stopped

networks:
  osint-network:
    driver: bridge
